// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjiOXnppvmGo1GBohiVAnsrSLXb7I2Aw',
    appId: '1:780801873809:web:2f0f401bb2f2f2b46a6c30',
    messagingSenderId: '780801873809',
    projectId: 'fluttbase-2b158',
    authDomain: 'fluttbase-2b158.firebaseapp.com',
    storageBucket: 'fluttbase-2b158.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iCARugIXQnuKrz_clfBxoXiVe21qmyc',
    appId: '1:780801873809:android:7fcaf370f73906346a6c30',
    messagingSenderId: '780801873809',
    projectId: 'fluttbase-2b158',
    storageBucket: 'fluttbase-2b158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqXN55nhgKbcjQJl-LfmPdbgAOVpxkYU',
    appId: '1:780801873809:ios:8d3a31234793e70b6a6c30',
    messagingSenderId: '780801873809',
    projectId: 'fluttbase-2b158',
    storageBucket: 'fluttbase-2b158.appspot.com',
    iosBundleId: 'com.example.fluttbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSqXN55nhgKbcjQJl-LfmPdbgAOVpxkYU',
    appId: '1:780801873809:ios:8d3a31234793e70b6a6c30',
    messagingSenderId: '780801873809',
    projectId: 'fluttbase-2b158',
    storageBucket: 'fluttbase-2b158.appspot.com',
    iosBundleId: 'com.example.fluttbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmjiOXnppvmGo1GBohiVAnsrSLXb7I2Aw',
    appId: '1:780801873809:web:80ff59e6bdec14796a6c30',
    messagingSenderId: '780801873809',
    projectId: 'fluttbase-2b158',
    authDomain: 'fluttbase-2b158.firebaseapp.com',
    storageBucket: 'fluttbase-2b158.appspot.com',
  );
}
